images:
- name: gardener-vpn-gateway
  sourceRepository: https://github.com/metal-stack/gardener-vpn-gateway
  repository: ghcr.io/metal-stack/gardener-vpn-gateway
  tag: "v0.1.1"
- name: fluent-bit
  sourceRepository: https://github.com/fluent/fluent-bit
  repository: fluent/fluent-bit
  tag: "2.1.10"
- name: audittailer
  sourceRepository: https://github.com/fluent/fluentd
  repository: fluent/fluentd
  tag: "v1.12"
